# Archivo de parámetros de configuración general
# Para el menú de la aplicación
pantalla:
  size: 50
  print: "*"
  option: "Seleccione la primera letra de la opción: "
  mistake: "Opción no válida. Inténtalo nuevamente."
# Para las funciones que puede invocar el menú principal
menu_principal:
  cabecera: Menú
  opciones:
    - desc: Ejecutar simulación
      func: e_function
    - desc: Consultar simulaciones
      func: while_menu
    - desc: Modificar archivo de configuración
      func: m_function
    - desc: Salir del programa
      func: s_function
# Para las funciones que puede invocar el menú de consulta
menu_consulta:
  cabecera: Consultas
  opciones:
    - desc: Ultima ejecución
      func: u_function
    - desc: Ejecucion específica
      func: e_c_function
    - desc: Regresar al menú anterior
      func: r_function
# Para la escritura de archivos de la aplicación y el backup correspondiente
directorio_salida: devices
directorio_backup: backup
directorio_report: reports
