mision:
  - ORBONE
  - CLNM
  - TMRS
  - GALXONE
  - UNKN
dispositivo:
  - satelite
  - nave espacial
  - vehiculo espacial
  - traje espacial
  - robot espacial
estado_dispositivo:
  - excelente
  - bueno
  - advertencia
  - defectuoso
  - inoperable
  - desconocido
mision_desconocida: UNKN
estado_desconocido: desconocido
unknown_miss_hash: unknown
estado_inoperable: inoperable
