periodo_simulacion: 10 # Inidad segundos. Por defecto 20 segundos 
tiempo_simulacion: 20 # Unidad segundos. Por defecto 60 segundos
max_num_reg: 100 # Limite superio de degistros a generar 
min_num_reg: 1 # Limite inferior de degistros a generar 
min_log_file: 1
max_log_file: 1000
min_lineas: 5
