periodo_simulacion: 20 # Inidad segundos. Por defecto 20 segundos 
tiempo_simulacion: 60 # Unidad segundos. Por defecto 60 segundos
num_registros: 50 # Cantidad de registros a generar por periodo de simulación. Por defecto 100