periodo_simulacion: 10 # Inidad segundos. Por defecto 20 segundos 
tiempo_simulacion: 20 # Unidad segundos. Por defecto 60 segundos
num_registros: 5 # Cantidad de registros a generar por periodo de simulación. Por defecto 100
