periodo_simulacion: 10 # Inidad segundos. Por defecto 20 segundos 
tiempo_simulacion: 20 # Unidad segundos. Por defecto 60 segundos
min_log_file: 1 # Valor mínimo para la generación del id del log
max_log_file: 1000 # Valor máximo para la generación del id del log
min_lineas: 5 # Información mínima que se espera en el archivo
min_num_reg: 1 # Limite inferior de degistros a generar
max_num_reg: 100 # Limite superio de degistros a generar 
